[main]
#Path in which you want to store the scraped data excel sheets
excel_file_path=news_webscraper.xlsx


[googlenews_query]
#Classes for the following tags used in the frontend script:

#Class for each Article Tag
article_class=IFHyqb DeXSAc
 #Under each article, Class for the div which contains the text
article_div_class=IL9Cne
#Inside that div, Class for the Anchor tag that contains href and "Headline"
anchor_tag_class=JtKRv
#The base link that is to be added to the href in anchor tag above to get "Link"
base_link=https://news.google.com/
#Class for div tag under the Article Tag that contains the Date Time Element
date_div_class=UOVeFe
#Class for Time Tag under the div tag that contains the datetime parameter
time_element_class=hvbAAd

#this is the url to which the 2 queries will be formatted and added to get an interactive dynamic environment
base_url_scraped=https://news.google.com/search?q=
#base_url_scraped+ "search_query"+when:+"num_days"+d



[googlenews_continous]
#Classes for the following tags used in the frontend script:

#Class for each Article Tag
article_class=IFHyqb DeXSAc
#Under each article, Class for the div which contains the text
article_div_class=IL9Cne
#Inside that div, Class for the Anchor tag that contains href and "Headline"
anchor_tag_class=JtKRv
#Class for div tag under the Article Tag that contains the Date Time Element
date_div_class=UOVeFe
#Class for Time Tag under the div tag that contains the datetime parameter
time_element_class=hvbAAd

#this is the url that is used to scrape the last 24h data
base_url_scraped=https://news.google.com/search?q=Larsen%%20and%%20Toubro%%20when%%3A1d&hl=en-IN&gl=IN&ceid=IN%%3Aen



[economictimes]
#Class for each Article
article_class=eachStory
#Each of the headlines of news are in h3 tags
title_size=h3
#Each href lies in a tag
anchor_tag=a
# base_link + the href gives us the link to the article
base_link=https://economictimes.indiatimes.com
 #Class for the div tag from which datetime can be extracted
date_div_class=storyDate

#this regular expression pattern has been used to carefully format and extract the numbers for the date as it is not uniform throughout the website
regex_pattern_for_date=(\d{2})[\S\s]*([A-Za-z]{3})[\S\s]*(\d{4})[\S\s]*(\d{2}[\S\s]*\d{2}[\S\s]*)IST

#this is the url that is used to scrape the data
base_url_scraped=https://economictimes.indiatimes.com/larsen-toubro-ltd/stocksupdate/companyid-13447.cms


[livemint]

#Class for each Article
article_class=jsx-abde3f138b2ad481 headlineSec 
#All the headlines of news have been in h2 tags
title_size=h2
#Each href lies in a tag
anchor_tag=a 

#In the livemint scraper, 3 Links are used: L&T, LTTS and LTIMindtree. 
base_url_scraped_larsentoubro=https://www.livemint.com/larsen-toubro/news/companyid-s0003025
base_url_scraped_ltts=https://www.livemint.com/lt-technology-services/news/companyid-s0003242
base_url_scraped_ltimindtree=https://www.livemint.com/lti-mindtree/news/companyid-s0003160

